### ISSUE TITLE
Add buttons to go to next and prev card question

### ISSUE THREAD

**Issue by shriyakalakata** [software-students-spring2024/2-web-app-exercise-gas2#64]
Suggested button use: "<" and ">"

**Comment by gboeker** [comment]
Or for cleaner design: click right half of card for next, and left half of card for back

**Comment by shriyakalakata** [comment]
> Or for cleaner design: click right half of card for next, and left half of card for back

Hmm good idea but it might not be intuitive for a user

**Comment by iltenahmet** [comment]
> > Or for cleaner design: click right half of card for next, and left half of card for back
> 
> Hmm good idea but it might not be intuitive for a user

Agreed, we shouldn't sacrifice ease of use for perceived aesthetic gains.
