### ISSUE TITLE
Bugs to be fixed and suggestions

### ISSUE THREAD

**Issue by shriyakalakata** [software-students-spring2024/2-web-app-exercise-gas2#73]
Bugs:
1. In the "example" deck, if I keep going back and forth, the "EDITED QUESTION!!" sometimes isn't shown where it's supposed to be
2. Added a second card to my new deck and I'm unable to click the next card button (or any button)(not working even if I log in again)

Suggestions:
1. Move error messages in log in and sign up pages to outside the card because it's messing up the input boxes style
2. Replace "delete deck" button with an "x"
3. Don't allow for multiple decks with the same name to be created by a user

**Comment by gboeker** [comment]
2 and 3 in suggestions is mentioned in issues #66 and #70
